# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: export
description: Export configurations to another place from your App Configuration store.
documentation:
    flag:
        appservice-account: ARM ID for AppService OR the name of the AppService, assuming it is in the same subscription and resource group as the App Configuration store. Required for AppService arguments
        auth-mode: This parameter can be used for indicating how a data operation is to be authorized. If the auth mode is "key", provide connection string or store name and your account access keys will be retrieved for authorization. If the auth mode is "login", provide the `--endpoint` or `--name` and your "az login" credentials will be used for authorization. You can configure the default auth mode using `az configure --defaults appconfig_auth_mode=<auth_mode>`. For more information, see https://learn.microsoft.com/azure/azure-app-configuration/concept-enable-rbac
        connection-string: Combination of access key and endpoint of the App Configuration store. Can be found using 'az appconfig credential list'. Users can preset it using `az configure --defaults appconfig_connection_string=<connection_string>` or environment variable with the name AZURE_APPCONFIG_CONNECTION_STRING.
        dest-auth-mode: Auth mode for connecting to the destination App Configuration store. For details, refer to "--auth-mode" argument.
        dest-label: Exported KVs will be labeled with this destination label. If neither --dest-label nor --preserve-labels is specified, will assign null label.
        destination: The destination of exporting. Note that exporting feature flags to appservice is not supported.
        endpoint: If auth mode is "login", provide endpoint URL of the App Configuration store. The endpoint can be retrieved using "az appconfig show" command. You can configure the default endpoint using `az configure --defaults appconfig_endpoint=<endpoint>`
        export-as-reference: Export key-values as App Configuration references. For more information, see https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references
        format: File format exporting to. Required for file arguments. Currently, feature flags are not supported in properties format.
        key: If no key specified, return all keys by default. Support star sign as filters, for instance abc* means keys with abc as prefix. Key filtering not applicable for feature flags. By default, all feature flags with specified label will be exported.
        label: Only keys and feature flags with this label will be exported. If no label specified, export keys and feature flags with null label by default. When export destination is appconfig, or when export destination is file with `appconfig/kvset` profile, this argument supports asterisk and comma signs for label filtering, for instance, * means all labels, abc* means labels with abc as prefix, and abc,xyz means labels with abc or xyz.
        name: Name of the App Configuration store. You can configure the default name using `az configure --defaults app_configuration_store=<name>`.
        naming-convention: 'Naming convention to be used for "Feature Management" section of file. Example: pascal = FeatureManagement, camel = featureManagement, underscore = feature_management, hyphen = feature-management.'
        path: Local configuration file path. Required for file arguments.
        prefix: Prefix to be trimmed from keys. Prefix will be ignored for feature flags.
        preserve-labels: Flag to preserve labels from source AppConfig. This argument should NOT be specified along with --dest-label.
        profile: Export profile to be used for exporting the key-values. Options 'depth', 'separator', 'naming-convention', 'prefix', 'dest-label' and, 'resolve-keyvault' are not supported when using 'appconfig/kvset' profile
        separator: 'Delimiter for flattening the key-value pairs to json or yaml file. Required for exporting hierarchical structure. Separator will be ignored for property files and feature flags. Supported values: ''.'', '','', '';'', ''-'', ''_'', ''__'', ''/'', '':'' '
        skip-features: Export items excluding all feature flags. By default, all features with the specified label will be exported to file or appconfig. Not applicable for appservice.
        skip-keyvault: Export items excluding all key vault references. By default, all key vault references with the specified label will be exported.
        snapshot: Export all keys in a given snapshot of the App Configuration store. If no snapshot is specified, the keys currently in the store are exported based on the specified key and label filters.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --appservice-account=: ARM ID for AppService OR the name of the AppService, assuming it is in the same subscription and resource group as the App Configuration store.
    --auth-mode=: This parameter can be used for indicating how a data operation is to be authorized.
    --connection-string=: Combination of access key and endpoint of the App Configuration store.
    --dest-auth-mode=: Auth mode for connecting to the destination App Configuration store.
    --dest-connection-string=: Combination of access key and endpoint of the destination store.
    --dest-endpoint=: If --dest-auth-mode is "login", provide endpoint URL of the destination App Configuration store.
    --dest-label=: Exported KVs will be labeled with this destination label.
    --dest-name=: The name of the destination App Configuration store.
    --endpoint=: If auth mode is "login", provide endpoint URL of the App Configuration store.
    --format=: File format exporting to.
    --key=: If no key specified, return all keys by default.
    --label=: Only keys and feature flags with this label will be exported.
    --naming-convention=: Naming convention to be used for "Feature Management" section of file.
    --path=: Local configuration file path.
    --prefix=: Prefix to be trimmed from keys.
    --preserve-labels=:
        description: Flag to preserve labels from source AppConfig.
        nargs: -1
    --profile=: Export profile to be used for exporting the key-values.
    --resolve-keyvault=:
        description: Resolve the content of key vault reference.
        nargs: -1
    --separator=: Delimiter for flattening the key-value pairs to json or yaml file.
    --skip-features=:
        description: Export items excluding all feature flags.
        nargs: -1
    --skip-keyvault=:
        description: Export items excluding all key vault references.
        nargs: -1
    --snapshot=: Export all keys in a given snapshot of the App Configuration store.
    --subscription=: Name or ID of subscription.
    -d, --destination=!: The destination of exporting.
    -n, --name=: Name of the App Configuration store.
    -r, --export-as-reference=:
        description: Export key-values as App Configuration references.
        nargs: -1
    -y, --yes=: Do not prompt for preview.
completion:
    flag:
        auth-mode:
            - login
            - key
        dest-auth-mode:
            - login
            - key
        destination:
            - file
            - appconfig
            - appservice
        export-as-reference:
            - "true"
            - "false"
        format:
            - json
            - yaml
            - properties
        naming-convention:
            - pascal
            - camel
            - underscore
            - hyphen
        preserve-labels:
            - "true"
            - "false"
        profile:
            - appconfig/default
            - appconfig/kvset
        resolve-keyvault:
            - "true"
            - "false"
        skip-features:
            - "true"
            - "false"
        skip-keyvault:
            - "true"
            - "false"
