# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: delete
description: Delete the hierarchy settings defined at the Management Group level.
flags:
    -n, --name=!: ""
    -y, --yes=: Do not prompt for confirmation.
