# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: Update an App Configuration store.
documentation:
    flag:
        arm-auth-mode: The authentication mode for accessing the App Configuration Store via ARM. 'pass-through' (Recommended) uses Microsoft Entra ID to access the store via ARM with proper authorization.'local' uses access keys for authentication. This requires access keys to be enabled.
        enable-arm-private-network-access: Enable access to the App Configuration store via ARM Private Link if resource is restricted to private network access. Requires Pass-through ARM authentication mode.
        enable-public-network: When true, requests coming from public networks have permission to access this store while private endpoint is enabled. When false, only requests made through Private Links can reach this store.
        enable-purge-protection: Property specifying whether protection against purge is enabled for this App Configuration store. Setting this property to true activates protection against purge for this App Configuration store and its contents. Enabling this functionality is irreversible.
        encryption-key-version: The version of the KeyVault key. Use the latest version by default.
        identity-client-id: Client ID of the managed identity with wrap and unwrap access to encryption key. Use system-assigned managed identity by default.
        name: Name of the App Configuration store. You can configure the default name using `az configure --defaults app_configuration_store=<name>`
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
        tags: 'space-separated tags: key[=value] [key[=value] ...]. Use '''' to clear existing tags.'
flags:
    --arm-auth-mode=: The authentication mode for accessing the App Configuration Store via ARM.
    --disable-local-auth=:
        description: Disable all authentication methods other than AAD authentication.
        nargs: -1
    --enable-arm-private-network-access=:
        description: Enable access to the App Configuration store via ARM Private Link if resource is restricted to private network access.
        nargs: -1
    --encryption-key-name=: The name of the KeyVault key.
    --encryption-key-vault=: The URI of the KeyVault.
    --encryption-key-version=: The version of the KeyVault key.
    --identity-client-id=: Client ID of the managed identity with wrap and unwrap access to encryption key.
    --sku=: The sku of the App Configuration store
    --subscription=: Name or ID of subscription.
    --tags=:
        description: 'space-separated tags: key[=value] [key[=value] ...].'
        nargs: -1
    -e, --enable-public-network=:
        description: When true, requests coming from public networks have permission to access this store while private endpoint is enabled.
        nargs: -1
    -g, --resource-group=: Name of resource group.
    -n, --name=!: Name of the App Configuration store.
    -p, --enable-purge-protection=:
        description: Property specifying whether protection against purge is enabled for this App Configuration store.
        nargs: -1
completion:
    flag:
        arm-auth-mode:
            - local
            - pass-through
        disable-local-auth:
            - "true"
            - "false"
        enable-arm-private-network-access:
            - "true"
            - "false"
        enable-public-network:
            - "true"
            - "false"
        enable-purge-protection:
            - "true"
            - "false"
        sku:
            - Free
            - Premium
            - Standard
