# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create hierarchy settings defined at the Management Group level.
flags:
    -m, --default-management-group=: ""
    -n, --name=!: ""
    -r, --require-authorization-for-group-creation=: ""
