# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create an App Configuration.
documentation:
    flag:
        arm-auth-mode: The authentication mode for accessing the App Configuration Store via ARM. 'pass-through' (Recommended) uses Microsoft Entra ID to access the store via ARM with proper authorization.'local' uses access keys for authentication. This requires access keys to be enabled.
        assign-identity: Space-separated list of managed identities to be assigned. Use "[system]" to refer to system-assigned managed identity or a resource ID to refer to user-assigned managed identity. If this argument is provided without any value, system-assigned managed identity will be assigned by default. If this argument is not provided, no managed identities will be assigned to this App Configuration store.
        enable-arm-private-network-access: Enable access to the App Configuration store via ARM Private Link if resource is restricted to private network access. Requires Pass-through ARM authentication mode.
        enable-public-network: When true, requests coming from public networks have permission to access this store while private endpoint is enabled. When false, only requests made through Private Links can reach this store.
        enable-purge-protection: Property specifying whether protection against purge is enabled for this App Configuration store. Setting this property to true activates protection against purge for this App Configuration store and its contents. Enabling this functionality is irreversible.
        location: 'Location. Values from: `az account list-locations`. You can configure the default location using `az configure --defaults location=<location>`.'
        name: Name of the App Configuration store. You can configure the default name using `az configure --defaults app_configuration_store=<name>`
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        retention-days: Number of days to retain the soft delete enabled App Configuration store after deleting. Must be a positive integer between 0 and 7.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --arm-auth-mode=: The authentication mode for accessing the App Configuration Store via ARM.
    --assign-identity=:
        description: Space-separated list of managed identities to be assigned.
        nargs: -1
    --disable-local-auth=:
        description: Disable all authentication methods other than AAD authentication.
        nargs: -1
    --enable-arm-private-network-access=:
        description: Enable access to the App Configuration store via ARM Private Link if resource is restricted to private network access.
        nargs: -1
    --no-replica=:
        description: Proceed without replica creation for premium tier store.
        nargs: -1
    --replica-location=: The location of the replica of the App Configuration store.
    --replica-name=: Name of the replica of the App Configuration store.
    --retention-days=: Number of days to retain the soft delete enabled App Configuration store after deleting.
    --sku=: The sku of the App Configuration store
    --subscription=: Name or ID of subscription.
    --tags=:
        description: 'Space-separated tags: key[=value] [key[=value] ...].'
        nargs: -1
    -e, --enable-public-network=:
        description: When true, requests coming from public networks have permission to access this store while private endpoint is enabled.
        nargs: -1
    -g, --resource-group=!: Name of resource group.
    -l, --location=!: Location.
    -n, --name=!: Name of the App Configuration store.
    -p, --enable-purge-protection=:
        description: Property specifying whether protection against purge is enabled for this App Configuration store.
        nargs: -1
completion:
    flag:
        arm-auth-mode:
            - local
            - pass-through
        disable-local-auth:
            - "true"
            - "false"
        enable-arm-private-network-access:
            - "true"
            - "false"
        enable-public-network:
            - "true"
            - "false"
        enable-purge-protection:
            - "true"
            - "false"
        no-replica:
            - "true"
            - "false"
        sku:
            - Free
            - Premium
            - Standard
