# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: Update a maintenance configuration of a managed Kubernetes cluster.
documentation:
    flag:
        day-of-month: Specify on which date of the month the maintenance occurs for AbsoluteMonthly schedule. e.g for the first day of the month use 1 as input, for fifteenth day of the month use 15 as input.
        day-of-week: Specify on which day of the week the maintenance occurs for Weekly or RelativeMonthly schedule. e.g Monday
        duration: The length of maintenance window. The value ranges from 4 to 24 hours.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        start-date: The date the maintenance window activates. e.g. 2023-01-01.
        start-hour: Maintenance start hour of 1 hour window on the weekday. e.g. 1 means 1:00am - 2:00am
        start-time: The start time of the maintenance window. e.g. 09:30.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
        utc-offset: The UTC offset in format +/-HH:mm. e.g. -08:00 or +05:30.
        week-index: Specify on which instance of the weekday specified in --day-of-week the maintenance occurs for RelativeMonthly schedule. The possible values are First, Second, Third, Fourth and Last.
        weekday: Weekday on which maintenance can happen. e.g. Monday
flags:
    --cluster-name=!: The cluster name.
    --config-file=: The config json file.
    --day-of-month=: Specify on which date of the month the maintenance occurs for AbsoluteMonthly schedule.
    --day-of-week=: Specify on which day of the week the maintenance occurs for Weekly or RelativeMonthly schedule.
    --duration=: The length of maintenance window.
    --interval-days=: The number of days between each set of occurrences for Daily schedule.
    --interval-months=: The number of months between each set of occurrences for AbsoluteMonthly or RelativeMonthly schedule.
    --interval-weeks=: The number of weeks between each set of occurrences for Weekly schedule.
    --schedule-type=: Schedule type for non-default maintenance configuration.
    --start-date=: The date the maintenance window activates.
    --start-hour=: Maintenance start hour of 1 hour window on the weekday.
    --start-time=: The start time of the maintenance window.
    --subscription=: Name or ID of subscription.
    --utc-offset=: The UTC offset in format +/-HH:mm.
    --week-index=: Specify on which instance of the weekday specified in --day-of-week the maintenance occurs for RelativeMonthly schedule.
    --weekday=: Weekday on which maintenance can happen.
    -g, --resource-group=!: Name of resource group.
    -n, --name=!: The config name.
completion:
    flag:
        schedule-type:
            - Daily
            - Weekly
            - AbsoluteMonthly
            - RelativeMonthly
        week-index:
            - First
            - Second
            - Third
            - Fourth
            - Last
