# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set
description: Contains information about an application in a Batch account.
documentation:
    flag:
        allow-updates: Specify to indicate whether packages within the application may be overwritten using the same version string. Specify either 'true' or 'false' to update the property.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --allow-updates=: Specify to indicate whether packages within the application may be overwritten using the same version string.
    --application-name=!: The name of the application.
    --default-version=: Specify which package to use if a client requests the application but does not specify a version.
    --display-name=: Specify the display name for the application.
    --subscription=: Name or ID of subscription.
    -g, --resource-group=!: Name of the resource group
    -n, --name=!: Name of the Batch account.
