# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: activate
description: Activates the specified application package.
documentation:
    flag:
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --application-name=!: The name of the application.
    --format=!: The format of the application package binary file.
    --subscription=: Name or ID of subscription.
    --version-name=!: The version name of the application.
    -g, --resource-group=!: Name of the resource group
    -n, --name=!: Name of the Batch account.
