# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: delete
description: Delete parameter persistence data.
documentation:
    flag:
        all: Clear all parameter persistence data. Either positional name argument  or --all can be specified.
        purge: Delete parameter persistence file from working directory. Only available when --all is specified.
        recursive: Indicate this is recursive delete of parameter persistence. Only available when --all is specified.
        "yes": Do not prompt for confirmation. Only available when --all is specified.
flags:
    --all=: Clear all parameter persistence data.
    --purge=: Delete parameter persistence file from working directory.
    --recursive=: Indicate this is recursive delete of parameter persistence.
    -y, --yes=: Do not prompt for confirmation.
