# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: storage-file
description: Preview the expected configurations of local connection to storage-file.
documentation:
    flag:
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --client-type=: The client type used on the connection
    --secret=:
        description: The secret auth info
        nargs: -1
    --subscription=: Name or ID of subscription.
completion:
    flag:
        client-type:
            - dotnet
            - dotnet-internal
            - java
            - python
            - nodejs
            - php
            - ruby
            - springBoot
            - none
