# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset
description: Unset a configuration.
documentation:
    flag:
        local: Include local configuration. Scan from the working directory up to the root drive, then the global configuration and unset the first occurrence.
flags:
    --local=: Include local configuration.
