# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: what-if
description: Execute a deployment What-If operation at tenant scope.
documentation:
    flag:
        location: 'Location. Values from: `az account list-locations`. You can configure the default location using `az configure --defaults location=<location>`.'
        name: The deployment name. Default to template file base name
        no-pretty-print: Disable pretty-print for What-If results. When set, the output format type will be used.
        no-prompt: The option to disable the prompt of missing parameters for ARM template. When the value is true, the prompt requiring users to provide missing parameter will be ignored. The default value is false.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --no-pretty-print=: Disable pretty-print for What-If results.
    --no-prompt=:
        description: The option to disable the prompt of missing parameters for ARM template.
        nargs: -1
    --subscription=: Name or ID of subscription.
    -f, --template-file=: a path to a template file or Bicep file in the file system
    -l, --location=!: Location.
    -n, --name=: The deployment name.
    -p, --parameters=:
        description: the deployment parameters
        nargs: -1
    -q, --query-string=: The query string (a SAS token) to be used with the template-uri in the case of linked templates.
    -r, --result-format=: ""
    -s, --template-spec=: The template spec resource id.
    -u, --template-uri=: a uri to a remote template file
    -x, --exclude-change-types=:
        description: Space-separated list of resource change types to be excluded from What-If results.
        nargs: -1
completion:
    flag:
        exclude-change-types:
            - Create
            - Delete
            - Ignore
            - Deploy
            - NoChange
            - Modify
            - Unsupported
        no-prompt:
            - "true"
            - "false"
        result-format:
            - ResourceIdOnly
            - FullResourcePayloads
