# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create a partner configuration.
documentation:
    flag:
        authorized-partner: Add authorized partner information. Multiple authorized partners can be specified by using more than one `--authorized-partner` argument
        default-maximum-expiration-time-in-days: Time used to validate the authorization expiration time for each authorized partner. If DefaultMaximumExpirationTimeInDays is not specified, the default is 7 days. Otherwise, allowed values are between 1 and 365 days.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
        tags: 'space-separated tags: key[=value] [key[=value] ...]. Use '''' to clear existing tags.'
flags:
    --authorized-partner=:
        description: Add authorized partner information.
        nargs: -1
    --default-maximum-expiration-time-in-days=: Time used to validate the authorization expiration time for each authorized partner.
    --subscription=: Name or ID of subscription.
    --tags=:
        description: 'space-separated tags: key[=value] [key[=value] ...].'
        nargs: -1
    -g, --resource-group=!: Name of resource group.
