# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create a deployment slot.
documentation:
    flag:
        configuration-source: source slot to clone configurations from. Use function app's name to refer to the production slot
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --configuration-source=: source slot to clone configurations from.
    --https-only=:
        description: Redirect all traffic made to an app using HTTP to HTTPS.
        nargs: -1
    --subscription=: Name or ID of subscription.
    -d, --registry-password=: The container registry server password
    -g, --resource-group=!: Name of resource group.
    -i, --image=: Container image, e.g. publisher/image-name:tag
    -n, --name=!: name of the function app
    -s, --slot=!: the name of the slot
    -u, --registry-username=: the container registry server username
completion:
    flag:
        https-only:
            - "true"
            - "false"
