# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set
description: Update an existing function app's runtime configuration.
documentation:
    flag:
        ids: One or more resource IDs (space-delimited). It should be a complete resource ID containing all information of 'Resource Id' arguments. You should provide either --ids or other 'Resource Id' arguments.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        runtime-version: The version of the functions runtime stack. Use "az functionapp list-flexconsumption-runtimes" to check supported runtimes and versions
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --ids=:
        description: One or more resource IDs (space-delimited).
        nargs: -1
    --runtime-version=!: The version of the functions runtime stack.
    --subscription=: Name or ID of subscription.
    -g, --resource-group=: Name of resource group.
    -n, --name=: name of the function app
