# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create a URL path map.
documentation:
    flag:
        default-address-pool: Name or ID of the default backend address pool. It is mandatory unless target type is redirection.
        default-http-settings: Name or ID of the default HTTP settings. It is mandatory unless target type is redirection.
        paths: Space-separated list of paths to associate with the rule. Valid paths start and end with "/", e.g, "/bar/".  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        rewrite-rule-set: Name or ID of the rewrite rule set. If not specified, the default for the map will be used.
        rules: Path rule of URL path map resource.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --address-pool=: Name or ID of the backend address pool to use with the created rule.
    --default-address-pool=: Name or ID of the default backend address pool.
    --default-http-settings=: Name or ID of the default HTTP settings.
    --default-redirect-config=: Name or ID of the default redirect configuration.
    --default-rewrite-rule-set=: Name or ID of the default rewrite rule set.
    --gateway-name=!: Name of the application gateway.
    --http-settings=: Name or ID of the HTTP settings to use with the created rule.
    --no-wait=:
        description: Do not wait for the long-running operation to finish.
        nargs: -1
    --paths=!:
        description: Space-separated list of paths to associate with the rule.
        nargs: -1
    --redirect-config=: Name or ID of the redirect configuration to use with the created rule.
    --rewrite-rule-set=: Name or ID of the rewrite rule set.
    --rule-name=: Name of the rule for a URL path map.
    --rules=:
        description: Path rule of URL path map resource.
        nargs: -1
    --subscription=: Name or ID of subscription.
    --waf-policy=: Name or ID of a web application firewall policy resource.
    -g, --resource-group=!: Name of resource group.
    -n, --name=!: Name of the URL path map.
completion:
    flag:
        no-wait:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
