# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set
description: Update the firewall configuration of a web application.
documentation:
    flag:
        disabled-rule-groups: Space-separated list of rule groups to disable. To disable individual rules, use `--disabled-rules`.
        ids: One or more resource IDs (space-delimited). It should be a complete resource ID containing all information of 'Resource Id' arguments. You should provide either --ids or other 'Resource Id' arguments.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --disabled-rule-groups=:
        description: Space-separated list of rule groups to disable.
        nargs: -1
    --disabled-rules=:
        description: Space-separated list of rule IDs to disable.
        nargs: -1
    --enabled=!: Specify whether the application firewall is enabled.
    --exclusion=:
        description: Add an exclusion expression to the WAF check.
        nargs: -1
    --file-upload-limit=: File upload size limit in MB.
    --firewall-mode=: Web application firewall mode.
    --gateway-name=: Name of the application gateway.
    --ids=:
        description: One or more resource IDs (space-delimited).
        nargs: -1
    --max-request-body-size=: Max request body size in KB.
    --no-wait=: Do not wait for the long-running operation to finish.
    --request-body-check=:
        description: Allow WAF to check the request body.
        nargs: -1
    --rule-set-type=: Rule set type.
    --rule-set-version=: Rule set version.
    --subscription=: Name or ID of subscription.
    -g, --resource-group=: Name of resource group.
completion:
    flag:
        enabled:
            - "true"
            - "false"
        firewall-mode:
            - detection
            - prevention
        request-body-check:
            - "true"
            - "false"
