# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: add
description: Add an inbound NAT rule to an IP configuration.
documentation:
    flag:
        inbound-nat-rule: Name or ID of an existing inbound NAT rule. If name is used, `--lb-name` must be specified.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --inbound-nat-rule=!: Name or ID of an existing inbound NAT rule.
    --lb-name=: Name of the load balancer
    --nic-name=!: Name of the network interface (NIC).
    --no-wait=:
        description: Do not wait for the long-running operation to finish.
        nargs: -1
    --subscription=: Name or ID of subscription.
    -g, --resource-group=!: Name of resource group.
    -n, --ip-config-name=!: Name of the IP configuration.
completion:
    flag:
        no-wait:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
