# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create a listener.
documentation:
    flag:
        frontend-ip: Name or ID of the frontend IP configuration. If only one exists, omit to use as default.
        host-names: List of Server Name Indications(SNI) for TLS Multi-site Listener that allows special wildcard characters as well.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --frontend-ip=: Name or ID of the frontend IP configuration.
    --frontend-port=!: Name or ID of the frontend port.
    --gateway-name=!: Name of the application gateway.
    --host-names=:
        description: List of Server Name Indications(SNI) for TLS Multi-site Listener that allows special wildcard characters as well.
        nargs: -1
    --no-wait=:
        description: Do not wait for the long-running operation to finish.
        nargs: -1
    --ssl-cert=: Name or ID of the SSL certificate to use.
    --ssl-profile-id=: Name or ID of the SSL profile to use.
    --subscription=: Name or ID of subscription.
    -g, --resource-group=!: Name of resource group.
    -n, --name=!: Name of the listener.
completion:
    flag:
        no-wait:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
