# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create HTTP settings.
documentation:
    flag:
        auth-certs: Space-separated list of authentication certificates (Names and IDs) to associate with the HTTP settings.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        connection-draining-timeout: Time in seconds after a backend server is removed during which on open connection remains active. Range from 0 (Disabled) to 3600.
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        root-certs: Space-separated list of trusted root certificates (Names and IDs) to associate with the HTTP settings. `--host-name` or `--host-name-from-backend-pool` is required when this field is set.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --affinity-cookie-name=: Name used for the affinity cookie.
    --auth-certs=:
        description: Space-separated list of authentication certificates (Names and IDs) to associate with the HTTP settings.
        nargs: -1
    --connection-draining-timeout=: Time in seconds after a backend server is removed during which on open connection remains active.
    --cookie-based-affinity=:
        description: Enable or disable cookie-based affinity.
        nargs: -1
    --enable-probe=:
        description: Whether the probe is enabled.
        nargs: -1
    --gateway-name=!: Name of the application gateway.
    --host-name-from-backend-pool=:
        description: Whether to pick host header should be picked from the host name of the backend server.
        nargs: -1
    --host-name=: Host header sent to the backend servers.
    --no-wait=:
        description: Do not wait for the long-running operation to finish.
        nargs: -1
    --path=: Path that will prefix all HTTP requests.
    --port=!: Number of the destination port on the backend.
    --probe=: Name or ID of the probe to associate with the HTTP settings.
    --protocol=: Protocol used to communicate with the backend.
    --root-certs=:
        description: Space-separated list of trusted root certificates (Names and IDs) to associate with the HTTP settings.
        nargs: -1
    --subscription=: Name or ID of subscription.
    --timeout=: Request timeout in seconds.
    -g, --resource-group=!: Name of resource group.
    -n, --name=!: Name of the backend http settings.
completion:
    flag:
        cookie-based-affinity:
            - Disabled
            - Enabled
        enable-probe:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
        host-name-from-backend-pool:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
        no-wait:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
        protocol:
            - Http
            - Https
            - Tcp
            - Tls
