# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: add
description: Add a new certificate to the Virtual Machine Scale Sets that make up the cluster to be used by hosted applications.
documentation:
    flag:
        resource-group: Specify the resource group name. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --certificate-file=: The existing certificate file path for the primary cluster certificate.
    --certificate-output-folder=: The folder of the new certificate file to be created.
    --certificate-password=: The password of the certificate file.
    --certificate-subject-name=: The subject name of the certificate to be created.
    --secret-identifier=: The existing Azure key vault secret URL
    --subscription=: Name or ID of subscription.
    --vault-name=: Azure key vault name, it not given it will be the cluster resource group name
    --vault-rg=: Key vault resource group name, if not given it will be cluster resource group name
    -c, --cluster-name=!: Specify the name of the cluster, if not given it will be same as resource group name
    -g, --resource-group=!: Specify the resource group name.
