# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create an attached database configuration.
documentation:
    flag:
        location: 'Location. Values from: `az account list-locations`. You can configure the default location using `az configure --defaults location=<location>`.'
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --attached-database-configuration-name=!: The name of the attached database configuration.
    --database-name=: The name of the database which you would like to attach, use * if you want to follow all current and future databases.
    --default-principals-modification-kind=: The default principals modification kind
    --kusto-pool-name=!: The name of the Kusto pool.
    --kusto-pool-resource-id=: The resource id of the kusto pool where the databases you would like to attach reside.
    --no-wait=: Do not wait for the long-running operation to finish.
    --subscription=: Name or ID of subscription.
    --table-level-sharing-properties=:
        description: Table level sharing specifications
        nargs: -1
    --workspace-name=!: The name of the workspace
    -g, --resource-group=!: Name of resource group.
    -l, --location=: Location.
completion:
    flag:
        default-principals-modification-kind:
            - Union
            - Replace
            - None
