# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get-default-config
description: Show the default config file which defines data to be collected.
documentation:
    flag:
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --is-windows-os=: for Windows VMs
    --subscription=: Name or ID of subscription.
