# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create
description: Create a deployment slot.
documentation:
    flag:
        configuration-source: source slot to clone configurations from. Use web app's name to refer to the production slot
        resource-group: Name of resource group. You can configure the default group using `az configure --defaults group=<name>`
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
flags:
    --configuration-source=: source slot to clone configurations from.
    --subscription=: Name or ID of subscription.
    -c, --container-image-name=: The container custom image name and optionally the tag name (e.g., `<registry-name>/<image-name>:<tag>`)
    -g, --resource-group=!: Name of resource group.
    -i, --deployment-container-image-name=: Container image name, e.g. publisher/image-name:tag
    -n, --name=!: Name of the webapp
    -r, --container-registry-url=: The container registry server url
    -s, --slot=!: the name of the slot
    -u, --container-registry-user=: The container registry server username
    -w, --container-registry-password=: The container registry server password
