# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Manage Azure CLI configuration.
commands:
    - name: get
      description: Get a configuration.
      flags:
        --local=: Include local configuration.
    - name: param-persist
      description: Manage parameter persistence.
      commands:
        - name: show
          description: Show parameter persistence data.
        - name: delete
          description: Delete parameter persistence data.
          flags:
            --all=: Clear all parameter persistence data.
            --purge=: Delete parameter persistence file from working directory.
            --recursive=: Indicate this is recursive delete of parameter persistence.
            -y, --yes=: Do not prompt for confirmation.
        - name: "on"
          description: Turn on parameter persistence.
        - name: "off"
          description: Turn off parameter persistence.
    - name: set
      description: Set a configuration.
      flags:
        --local=: Set as a local configuration in the working directory.
    - name: unset
      description: Unset a configuration.
      flags:
        --local=: Include local configuration.
