# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: configure
description: configure
commands:
    - name: configure
      description: Manage Azure CLI configuration.
      flags:
        --___SUBSCRIPTION=:
            description: ==SUPPRESS==
            nargs: -1
        --cmd=:
            description: ==SUPPRESS==
            nargs: -1
        --scope=: scope of defaults.
        -d, --defaults=:
            nargs: -1
        -l, --list-defaults=:
            description: list all applicable defaults
            nargs: -1
      completion:
        flag:
            list-defaults:
                - "true"
                - "false"
            scope:
                - global
                - local
