# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: deployment-scripts
description: Manage deployment scripts at subscription or resource group scope.
commands:
    - name: delete
      description: Delete a deployment script.
      flags:
        --name=!: Deployment script resource name.
        --subscription=: Name or ID of subscription.
        -g, --resource-group=!: Name of resource group.
        -y, --yes=: Do not prompt for confirmation.
    - name: list
      description: List all deployment scripts.
      flags:
        --subscription=: Name or ID of subscription.
        -g, --resource-group=: Name of resource group.
    - name: show
      description: Retrieve a deployment script.
      flags:
        --name=!: Deployment script resource name.
        --subscription=: Name or ID of subscription.
        -g, --resource-group=!: Name of resource group.
    - name: show-log
      description: Show deployment script logs.
      flags:
        --name=!: Deployment script resource name.
        --subscription=: Name or ID of subscription.
        -g, --resource-group=!: Name of resource group.
