# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: deployment-scripts
description: deployment-scripts
commands:
    - name: delete
      flags:
        --cmd=:
            description: ==SUPPRESS==
            nargs: -1
        --name=!: ""
        --subscription=: Name or ID of subscription.
        -g, --resource-group=!: Name of resource group.
        -y, --yes=: Do not prompt for confirmation.
    - name: list
      flags:
        --cmd=:
            description: ==SUPPRESS==
            nargs: -1
        --subscription=: Name or ID of subscription.
        -g, --resource-group=: Name of resource group.
    - name: show
      flags:
        --cmd=:
            description: ==SUPPRESS==
            nargs: -1
        --name=!: ""
        --subscription=: Name or ID of subscription.
        -g, --resource-group=!: Name of resource group.
    - name: show-log
      flags:
        --cmd=:
            description: ==SUPPRESS==
            nargs: -1
        --name=!: ""
        --subscription=: Name or ID of subscription.
        -g, --resource-group=!: Name of resource group.
