package azcli

func init() {
	services = map[string]string{
		"account":             "Manage Azure subscription information.",
		"acr":                 "Manage private registries with Azure Container Registries.",
		"ad":                  "Manage Microsoft Entra ID (formerly known as Azure Active Directory, Azure AD, AAD) entities needed for Azure role-based access control (Azure RBAC) through Microsoft Graph API.",
		"advisor":             "Manage Azure Advisor.",
		"afd":                 "Manage Azure Front Door Standard/Premium.",
		"aks":                 "Manage Azure Kubernetes Services.",
		"ams":                 "Manage Azure Media Services resources.",
		"apim":                "Manage Azure API Management services.",
		"appconfig":           "Manage App Configurations.",
		"appservice":          "Manage App Service plans.",
		"aro":                 "Manage Azure Red Hat OpenShift clusters.",
		"backup":              "Manage Azure Backups.",
		"batch":               "Manage Azure Batch.",
		"batchai":             "Manage Batch AI resources.",
		"bicep":               "Bicep CLI command group.",
		"billing":             "Manage Azure Billing.",
		"bot":                 "Manage Microsoft Azure Bot Service.",
		"cache":               "Commands to manage CLI objects cached using the `--defer` argument.",
		"capacity":            "Manage capacity.",
		"cdn":                 "Manage Azure Content Delivery Networks (CDNs).",
		"cloud":               "Manage registered Azure clouds.",
		"cognitiveservices":   "Manage Azure Cognitive Services accounts.",
		"compute-fleet":       "Manage for Azure Compute Fleet",
		"compute-recommender": "Manage sku/zone/region recommender info for compute resources",
		"config":              "Manage Azure CLI configuration.",
		"connection":          "Commands to manage Service Connector local connections which allow local environment to connect Azure Resource. If you want to manage connection for compute service, please run 'az webapp/containerapp/spring connection'",
		"consumption":         "Manage consumption of Azure resources.",
		"container":           "Manage Azure Container Instances.",
		"containerapp":        "Manage Azure Container Apps.",
		"cosmosdb":            "Manage Azure Cosmos DB database accounts.",
		"data-boundary":       "data boundary operations",
		"databoxedge":         "Manage device with databoxedge.",
		"demo":                "Demos for designing, developing and demonstrating Azure CLI.",
		"deployment-scripts":  "Manage deployment scripts at subscription or resource group scope.",
		"deployment":          "Manage Azure Resource Manager template deployment at subscription scope.",
		"disk-access":         "Manage disk access resources.",
		"disk-encryption-set": "Disk Encryption Set resource.",
		"disk":                "Manage Azure Managed Disks.",
		"dls":                 "Manage Data Lake Store accounts and filesystems.",
		"dms":                 "Manage Azure Data Migration Service (classic) instances.",
		"eventgrid":           "Manage Azure Event Grid topics, domains, domain topics, system topics partner topics, event subscriptions, system topic event subscriptions and partner topic event subscriptions.",
		"eventhubs":           "eventhubs",
		"extension":           "Manage and update CLI extensions.",
		"feature":             "Manage resource provider features.",
		"functionapp":         "Manage function apps. To install the Azure Functions Core tools see https://github.com/Azure/azure-functions-core-tools",
		"group":               "Manage resource groups and template deployments.",
		"hdinsight":           "Manage HDInsight resources.",
		"identity":            "Managed Identities",
		"image":               "Manage custom virtual machine images.",
		"iot":                 "Manage Internet of Things (IoT) assets.",
		"keyvault":            "Manage KeyVault keys, secrets, and certificates.",
		"lab":                 "Manage azure devtest labs.",
		"lock":                "Manage Azure locks.",
		"logicapp":            "Manage logic apps.",
		"managed-cassandra":   "Azure Managed Cassandra.",
		"managedapp":          "Manage template solutions provided and maintained by Independent Software Vendors (ISVs).",
		"managedservices":     "Manage the registration assignments and definitions in Azure.",
		"maps":                "Manage Azure Maps.",
		"mariadb":             "Manage Azure Database for MariaDB servers.",
		"monitor":             "Manage the Azure Monitor Service.",
		"mysql":               "Manage Azure Database for MySQL servers.",
		"netappfiles":         "Manage Azure NetApp Files (ANF) Resources",
		"network":             "Manage Azure Network resources.",
		"policy":              "Manage resource policies.",
		"postgres":            "Manage Azure Database for PostgreSQL servers.",
		"ppg":                 "Manage Proximity Placement Groups.",
		"private-link":        "private-link association CLI command group.",
		"provider":            "Manage resource providers.",
		"redis":               "Manage dedicated Redis caches for your Azure applications.",
		"relay":               "Manage Azure Relay Service namespaces, WCF relays, hybrid connections, and rules.",
		"resource":            "Manage Azure resources.",
		"resourcemanagement":  "resourcemanagement CLI command group.",
		"restore-point":       "Manage restore point with res.",
		"role":                "Manage Azure role-based access control (Azure RBAC).",
		"search":              "Manage Azure Search services, admin keys and query keys",
		"security":            "Manage your security posture with Microsoft Defender for Cloud.",
		"servicebus":          "servicebus",
		"sf":                  "Manage and administer Azure Service Fabric clusters.",
		"sig":                 "Manage shared image gallery.",
		"signalr":             "Manage Azure SignalR Service.",
		"snapshot":            "Manage point-in-time copies of managed disks, native blobs, or other snapshots.",
		"sql":                 "Manage Azure SQL Databases and Data Warehouses.",
		"sshkey":              "Manage ssh public key with vm",
		"stack":               "A deployment stack is a native Azure resource type that enables you to perform operations on a resource collection as an atomic unit.",
		"staticwebapp":        "Manage static apps.",
		"storage":             "Manage Azure Cloud Storage resources.",
		"synapse":             "Manage and operate Synapse Workspace, Spark Pool, SQL Pool.",
		"tag":                 "Tag Management on a resource.",
		"term":                "Manage marketplace agreement with marketplaceordering",
		"ts":                  "Manage template specs at subscription or resource group scope.",
		"vm":                  "Manage Linux or Windows virtual machines.",
		"vmss":                "Manage groupings of virtual machines in an Azure Virtual Machine Scale Set (VMSS).",
		"webapp":              "Manage web apps.",
	}
}
